year = input("What year is it? ")
print("\t \t \t \t \t \t. \t: \t.")
print("\t \t \t  \t \t  '. \t: \t  .'")
print("\tHAPPY NEW YEAR \t. \t'. \t: \t.' \t.")
print("\t !!!", year, "!!! \t. \t'. \t: \t.' \t.")
print("\t \t \t  \t \t  '. \t: \t  .'")
print("\t \t \t \t \t \t. \t: \t.")